/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import chooseandtravel.Datos_Buses;
import chooseandtravel.Datos_Cuentas;
import chooseandtravel.Datos_Empresa;
import chooseandtravel.Datos_Viajes;
import chooseandtravel.Sistema;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author kuuzou
 */
public class ClienteVentana extends javax.swing.JFrame {

    Sistema sistema;
    Datos_Cuentas mCuentas= new Datos_Cuentas();
    Datos_Empresa mSuc = new Datos_Empresa();
    Datos_Viajes mViajes = new Datos_Viajes();
    Datos_Buses mBuses = new Datos_Buses();
    private ArrayList<JLabel> asientos = new ArrayList<JLabel>();
    private int asiento;

    /**
     *
     * @param system
     */
    public ClienteVentana(Sistema system) {
        sistema = system;
        sistema.inicio();
        initComponents();
        addAsientos();
        reload();
        this.setLocationRelativeTo(null);
    }

    /**
     *
     */
    public void reload() {
        asiento=0;
        this.fechaViaje.getDateEditor().setEnabled(false);
        for (JLabel n : asientos) {
            n.setVisible(false);
        }
    }

    /**
     *
     */
    public void addAsientos() {
        asientos.add(a1);
        asientos.add(a2);
        asientos.add(a3);
        asientos.add(a4);
        asientos.add(a5);
        asientos.add(a6);
        asientos.add(a7);
        asientos.add(a8);
        asientos.add(a9);
        asientos.add(a10);
        asientos.add(a11);
        asientos.add(a12);
        asientos.add(a13);
        asientos.add(a14);
        asientos.add(a15);
        asientos.add(a16);
        asientos.add(a17);
        asientos.add(a18);
        asientos.add(a19);
        asientos.add(a20);
        asientos.add(a21);
        asientos.add(a22);
        asientos.add(a23);
        asientos.add(a24);
        asientos.add(a25);

    }

    /**
     *
     * @param a
     */
    public void setAsientos(JLabel a) {
        for (int n = 0; n < asientos.size(); n++) {
            if ((asientos.get(n)).equals(a)) {
                ImageIcon icoPressed = new ImageIcon(getClass().getResource("/Imagenes/asientos/" + (n + 1) + "Pressed.png"));
                a.setIcon(icoPressed);
                asiento = (n + 1);
            } else {
                ImageIcon icoDefault = new ImageIcon(getClass().getResource("/Imagenes/asientos/" + (n + 1) + "Default.png"));
                (asientos.get(n)).setIcon(icoDefault);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cerrarSesionB = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        usuariosPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        a2 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        a4 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        a5 = new javax.swing.JLabel();
        a6 = new javax.swing.JLabel();
        a7 = new javax.swing.JLabel();
        a8 = new javax.swing.JLabel();
        a9 = new javax.swing.JLabel();
        a10 = new javax.swing.JLabel();
        a11 = new javax.swing.JLabel();
        a12 = new javax.swing.JLabel();
        a13 = new javax.swing.JLabel();
        a14 = new javax.swing.JLabel();
        a15 = new javax.swing.JLabel();
        a16 = new javax.swing.JLabel();
        a17 = new javax.swing.JLabel();
        a18 = new javax.swing.JLabel();
        a19 = new javax.swing.JLabel();
        a20 = new javax.swing.JLabel();
        a21 = new javax.swing.JLabel();
        a22 = new javax.swing.JLabel();
        a23 = new javax.swing.JLabel();
        a24 = new javax.swing.JLabel();
        a25 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        sucOrigenComboBox = new javax.swing.JComboBox<>();
        sucDestinoComboBox = new javax.swing.JComboBox<>();
        horario1 = new javax.swing.JRadioButton();
        horario3 = new javax.swing.JRadioButton();
        horario2 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        fechaViaje = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        configPanel = new javax.swing.JPanel();
        configTabPanel = new javax.swing.JTabbedPane();
        cuentasTabPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        modCuenta_user = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(990, 750));

        jPanel5.setBackground(new java.awt.Color(38, 188, 140));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 172, 127), 3, true));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText(sistema.getSesion());
        jTextField1.setEnabled(false);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Conectado como:");

        cerrarSesionB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrarsesionDefault.png"))); // NOI18N
        cerrarSesionB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cerrarSesionBMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cerrarSesionBMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarSesionBMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarSesionBMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarSesionBMouseEntered(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/userIcon32x32.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cerrarSesionB)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(cerrarSesionB)
                .addContainerGap())
        );

        jTabbedPane1.setBackground(new java.awt.Color(102, 102, 102));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jTable2.setModel(mViajes.viajesToTable(sistema.getSesion(), sistema.getViajes())
        );
        jTable2.setEnabled(false);
        jScrollPane8.setViewportView(jTable2);

        jLabel2.setText("Resumen de Viajes");

        jLabel10.setText("Informacion de Usuario");

        jTextField2.setEditable(false);
        jTextField2.setText(sistema.getSesion());

        jLabel11.setText("Nombre");

        jLabel12.setText("Sucursal");

        jTextField3.setEditable(false);
        jTextField3.setText(mCuentas.SucursalDeUser(sistema.getCuentas(), sistema.getSesion(), sistema.getSucursales())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jTextField3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Resumen", jPanel4);

        usuariosPanel.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setText("Seleccionar sucursal de origen:");

        jLabel4.setText("Seleccionar sucursal de destino:");

        jLabel5.setText("Seleccionar Horario de viaje:");

        jLabel6.setText("Seleccionar asiento:");

        a2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/2Default.png"))); // NOI18N
        a2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a2MouseClicked(evt);
            }
        });

        a1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/1Default.png"))); // NOI18N
        a1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a1MouseClicked(evt);
            }
        });

        a4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/4Default.png"))); // NOI18N
        a4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a4MouseClicked(evt);
            }
        });

        a3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/3Default.png"))); // NOI18N
        a3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a3MouseClicked(evt);
            }
        });

        a5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/5Default.png"))); // NOI18N
        a5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a5MouseClicked(evt);
            }
        });

        a6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/6Default.png"))); // NOI18N
        a6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a6MouseClicked(evt);
            }
        });

        a7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/7Default.png"))); // NOI18N
        a7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a7MouseClicked(evt);
            }
        });

        a8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/8Default.png"))); // NOI18N
        a8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a8MouseClicked(evt);
            }
        });

        a9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/9Default.png"))); // NOI18N
        a9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a9MouseClicked(evt);
            }
        });

        a10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/10Default.png"))); // NOI18N
        a10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a10MouseClicked(evt);
            }
        });

        a11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/11Default.png"))); // NOI18N
        a11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a11MouseClicked(evt);
            }
        });

        a12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/12Default.png"))); // NOI18N
        a12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a12MouseClicked(evt);
            }
        });

        a13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/13Default.png"))); // NOI18N
        a13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a13MouseClicked(evt);
            }
        });

        a14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/14Default.png"))); // NOI18N
        a14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a14MouseClicked(evt);
            }
        });

        a15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/15Default.png"))); // NOI18N
        a15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a15MouseClicked(evt);
            }
        });

        a16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/16Default.png"))); // NOI18N
        a16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a16MouseClicked(evt);
            }
        });

        a17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/17Default.png"))); // NOI18N
        a17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a17MouseClicked(evt);
            }
        });

        a18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/18Default.png"))); // NOI18N
        a18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a18MouseClicked(evt);
            }
        });

        a19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/19Default.png"))); // NOI18N
        a19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a19MouseClicked(evt);
            }
        });

        a20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/20Default.png"))); // NOI18N
        a20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a20MouseClicked(evt);
            }
        });

        a21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/21Default.png"))); // NOI18N
        a21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a21MouseClicked(evt);
            }
        });

        a22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/22Default.png"))); // NOI18N
        a22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a22MouseClicked(evt);
            }
        });

        a23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/23Default.png"))); // NOI18N
        a23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a23MouseClicked(evt);
            }
        });

        a24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/24Default.png"))); // NOI18N
        a24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a24MouseClicked(evt);
            }
        });

        a25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos/25Default.png"))); // NOI18N
        a25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a25MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(a2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a23))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(a1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a22))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(a3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a25)))
                .addGap(111, 111, 111))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(a8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(a11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(a14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(a17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(a20, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(a24)
                            .addComponent(a6)
                            .addComponent(a3)
                            .addComponent(a9)
                            .addComponent(a12)
                            .addComponent(a15)
                            .addComponent(a18)
                            .addComponent(a21)
                            .addComponent(a25))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(a23, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a4)
                    .addComponent(a1)
                    .addComponent(a13)
                    .addComponent(a7)
                    .addComponent(a10)
                    .addComponent(a16)
                    .addComponent(a19)
                    .addComponent(a22))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jButton1.setText("Solicitar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sucOrigenComboBox.setModel(mSuc.arrayToComboBox(sistema.getSucursales())
        );
        sucOrigenComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucOrigenComboBoxActionPerformed(evt);
            }
        });

        sucDestinoComboBox.setModel(mSuc.arrayToComboBoxToDestino(sistema.getSucursales(), (String)sucOrigenComboBox.getSelectedItem())
        );

        horario1.setText("07:30 hrs");
        horario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horario1ActionPerformed(evt);
            }
        });

        horario3.setText("19:30 hrs");
        horario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horario3ActionPerformed(evt);
            }
        });

        horario2.setText("12:30 hrs");
        horario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horario2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Elegir fecha del viaje:");

        jButton2.setText("Ver Asientos Disponibles");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usuariosPanelLayout = new javax.swing.GroupLayout(usuariosPanel);
        usuariosPanel.setLayout(usuariosPanelLayout);
        usuariosPanelLayout.setHorizontalGroup(
            usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuariosPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuariosPanelLayout.createSequentialGroup()
                        .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaViaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuariosPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sucOrigenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuariosPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sucDestinoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuariosPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(horario1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(horario2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(horario3)))
                .addContainerGap())
        );
        usuariosPanelLayout.setVerticalGroup(
            usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosPanelLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sucOrigenComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(sucDestinoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(horario3)
                        .addComponent(horario2)
                        .addComponent(horario1)))
                .addGap(20, 20, 20)
                .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fechaViaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Solicitar Viaje", usuariosPanel);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jTable1.setModel(mViajes.viajesHistorialUser(sistema.getSesion(), sistema.getViajes())
        );
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Historial", jPanel2);

        configPanel.setBackground(new java.awt.Color(102, 102, 102));

        configTabPanel.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("*Modificar parametros de cuentas, se puden cambiar \n contraseñas de cuentas de usuario, y la informacion de\n la cuenta (nombre y apellido) de usuario.");
        jScrollPane2.setViewportView(jTextArea2);

        modCuenta_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mod-cuentaDefault.png"))); // NOI18N
        modCuenta_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modCuenta_userMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                modCuenta_userMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modCuenta_userMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modCuenta_userMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modCuenta_userMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout cuentasTabPanelLayout = new javax.swing.GroupLayout(cuentasTabPanel);
        cuentasTabPanel.setLayout(cuentasTabPanelLayout);
        cuentasTabPanelLayout.setHorizontalGroup(
            cuentasTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuentasTabPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(cuentasTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modCuenta_user))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        cuentasTabPanelLayout.setVerticalGroup(
            cuentasTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuentasTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modCuenta_user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        configTabPanel.addTab("Cuentas", cuentasTabPanel);

        javax.swing.GroupLayout configPanelLayout = new javax.swing.GroupLayout(configPanel);
        configPanel.setLayout(configPanelLayout);
        configPanelLayout.setHorizontalGroup(
            configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(configTabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        configPanelLayout.setVerticalGroup(
            configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(configTabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(469, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Configuracion", configPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarSesionBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionBMousePressed
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/cerrarsesionPressed.png"));
        this.cerrarSesionB.setIcon(ico);
    }//GEN-LAST:event_cerrarSesionBMousePressed

    private void cerrarSesionBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionBMouseReleased
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/cerrarsesionDefault.png"));
        this.cerrarSesionB.setIcon(ico);
    }//GEN-LAST:event_cerrarSesionBMouseReleased

    private void cerrarSesionBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionBMouseClicked
        dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_cerrarSesionBMouseClicked

    private void cerrarSesionBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionBMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/cerrarsesionDefault.png"));
        this.cerrarSesionB.setIcon(ico);
    }//GEN-LAST:event_cerrarSesionBMouseExited

    private void cerrarSesionBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionBMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/cerrarsesionHover.png"));
        this.cerrarSesionB.setIcon(ico);
    }//GEN-LAST:event_cerrarSesionBMouseEntered

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void modCuenta_userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modCuenta_userMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/mod-cuentaHover.png"));
        this.modCuenta_user.setIcon(ico);
    }//GEN-LAST:event_modCuenta_userMouseEntered

    private void modCuenta_userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modCuenta_userMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/mod-cuentaDefault.png"));
        this.modCuenta_user.setIcon(ico);
    }//GEN-LAST:event_modCuenta_userMouseExited

    private void modCuenta_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modCuenta_userMouseClicked
        UserModCuenta ventana = new UserModCuenta(sistema);
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modCuenta_userMouseClicked

    private void modCuenta_userMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modCuenta_userMouseReleased
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/mod-cuentaDefault.png"));
        this.modCuenta_user.setIcon(ico);
    }//GEN-LAST:event_modCuenta_userMouseReleased

    private void modCuenta_userMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modCuenta_userMousePressed
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/mod-cuentaPressed.png"));
        this.modCuenta_user.setIcon(ico);
    }//GEN-LAST:event_modCuenta_userMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String empresa = "turbus";
        String origen = (String) sucOrigenComboBox.getSelectedItem();
        String destino = (String) sucDestinoComboBox.getSelectedItem();
        String horario = null;
        if (horario1.isSelected()) {
            horario = "07:30";
        } else {
            if (horario2.isSelected()) {
                horario = "12:30";
            } else {
                if (horario3.isSelected()) {
                    horario = "19:30";
                }
            }
        }
        String fecha = new SimpleDateFormat("dd/MM/yyyy").format(fechaViaje.getDate());
        String nombre = sistema.getSesion();
        if(horario1.isSelected()!=true&&horario2.isSelected()!=true&&horario3.isSelected()!=true){
            JOptionPane.showMessageDialog(this, "Seleccionar un horario del viaje","Error",JOptionPane.WARNING_MESSAGE);
        }else{
            if(asiento==0){
                JOptionPane.showMessageDialog(this, "Seleccionar un asiento disponible","Error",JOptionPane.WARNING_MESSAGE);
            }else{
                if(fecha.equals("")||fecha.equals(null)){
                    JOptionPane.showMessageDialog(this, "Seleccionar un fecha para el viaje","Error",JOptionPane.WARNING_MESSAGE);
                }else{
                mViajes.agregarViaje(origen, destino, horario, fecha, asiento, nombre);

                }
            }
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void sucOrigenComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucOrigenComboBoxActionPerformed
        this.sucDestinoComboBox.setModel(mSuc.arrayToComboBoxToDestino(sistema.getSucursales(), (String) sucOrigenComboBox.getSelectedItem()));
    }//GEN-LAST:event_sucOrigenComboBoxActionPerformed

    private void horario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horario1ActionPerformed
        if (this.horario1.isSelected()) {
            horario2.setSelected(false);
            horario3.setSelected(false);
        }
    }//GEN-LAST:event_horario1ActionPerformed

    private void horario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horario2ActionPerformed
        if (this.horario2.isSelected()) {
            horario1.setSelected(false);
            horario3.setSelected(false);
        }
    }//GEN-LAST:event_horario2ActionPerformed

    private void horario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horario3ActionPerformed
        if (this.horario3.isSelected()) {
            horario1.setSelected(false);
            horario2.setSelected(false);
        }
    }//GEN-LAST:event_horario3ActionPerformed

    private void a1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1MouseClicked
        setAsientos(a1);
    }//GEN-LAST:event_a1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String empresa = "turbus";
        String origen = (String) sucOrigenComboBox.getSelectedItem();
        String destino = (String) sucDestinoComboBox.getSelectedItem();
        String horario = null;
        if (horario1.isSelected()) {
            horario = "07:30";
        } else {
            if (horario2.isSelected()) {
                horario = "12:30";
            } else {
                if (horario3.isSelected()) {
                    horario = "19:30";
                }
            }
        }
        String fecha = new SimpleDateFormat("dd/MM/yyyy").format(fechaViaje.getDate());
        for (int n = 0; n < mBuses.getAsientos(sistema.getBuses(), empresa, origen, destino, horario, fecha).length; n++) {
            if (mBuses.getAsientos(sistema.getBuses(), empresa, origen, destino, horario, fecha)[n] == 0) {
                if (n == 0) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/1ND.png"));
                    this.a1.setDisabledIcon(ico);
                    this.a1.setEnabled(false);
                }
                if (n == 1) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/2ND.png"));
                    this.a2.setDisabledIcon(ico);
                    this.a2.setEnabled(false);
                }
                if (n == 2) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/3ND.png"));
                    this.a3.setDisabledIcon(ico);
                    this.a3.setEnabled(false);
                }
                if (n == 3) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/4ND.png"));
                    this.a4.setDisabledIcon(ico);
                    this.a4.setEnabled(false);
                }
                if (n == 4) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/5ND.png"));
                    this.a5.setDisabledIcon(ico);
                    this.a5.setEnabled(false);
                }
                if (n == 5) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/6ND.png"));
                    this.a6.setDisabledIcon(ico);
                    this.a6.setEnabled(false);
                }
                if (n == 6) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/7ND.png"));
                    this.a7.setDisabledIcon(ico);
                    this.a7.setEnabled(false);
                }
                if (n == 7) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/8ND.png"));
                    this.a8.setDisabledIcon(ico);
                    this.a8.setEnabled(false);
                }
                if (n == 8) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/9ND.png"));
                    this.a9.setDisabledIcon(ico);
                    this.a9.setEnabled(false);
                }
                if (n == 9) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/10ND.png"));
                    this.a10.setDisabledIcon(ico);
                    this.a10.setEnabled(false);
                }
                if (n == 10) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/11ND.png"));
                    this.a11.setDisabledIcon(ico);
                    this.a11.setEnabled(false);
                }
                if (n == 11) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/12ND.png"));
                    this.a12.setDisabledIcon(ico);
                    this.a12.setEnabled(false);
                }
                if (n == 12) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/13ND.png"));
                    this.a13.setDisabledIcon(ico);
                    this.a13.setEnabled(false);
                }
                if (n == 13) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/14ND.png"));
                    this.a14.setDisabledIcon(ico);
                    this.a14.setEnabled(false);
                }
                if (n == 14) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/15ND.png"));
                    this.a15.setDisabledIcon(ico);
                    this.a15.setEnabled(false);
                }
                if (n == 15) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/16ND.png"));
                    this.a16.setDisabledIcon(ico);
                    this.a16.setEnabled(false);
                }
                if (n == 16) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/17ND.png"));
                    this.a17.setDisabledIcon(ico);
                    this.a17.setEnabled(false);
                }
                if (n == 17) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/18ND.png"));
                    this.a18.setDisabledIcon(ico);
                    this.a18.setEnabled(false);
                }
                if (n == 18) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/19ND.png"));
                    this.a19.setDisabledIcon(ico);
                    this.a19.setEnabled(false);
                }
                if (n == 19) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/20ND.png"));
                    this.a20.setDisabledIcon(ico);
                    this.a20.setEnabled(false);
                }
                if (n == 20) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/21ND.png"));
                    this.a21.setDisabledIcon(ico);
                    this.a21.setEnabled(false);
                }
                if (n == 21) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/22ND.png"));
                    this.a22.setDisabledIcon(ico);
                    this.a22.setEnabled(false);
                }
                if (n == 22) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/23ND.png"));
                    this.a23.setDisabledIcon(ico);
                    this.a23.setEnabled(false);
                }
                if (n == 23) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/24ND.png"));
                    this.a24.setDisabledIcon(ico);
                    this.a24.setEnabled(false);
                }
                if (n == 24) {
                    ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/asientos/25ND.png"));
                    this.a25.setDisabledIcon(ico);
                    this.a25.setEnabled(false);
                }
                for (JLabel a : asientos) {
                    a.setVisible(true);
                }

            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void a2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a2MouseClicked
        setAsientos(this.a2);
    }//GEN-LAST:event_a2MouseClicked

    private void a3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a3MouseClicked
        setAsientos(this.a3);
    }//GEN-LAST:event_a3MouseClicked

    private void a4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a4MouseClicked
        setAsientos(this.a4);
    }//GEN-LAST:event_a4MouseClicked

    private void a5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a5MouseClicked
        setAsientos(this.a5);
    }//GEN-LAST:event_a5MouseClicked

    private void a6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a6MouseClicked
        setAsientos(this.a6);
    }//GEN-LAST:event_a6MouseClicked

    private void a7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a7MouseClicked
        setAsientos(this.a7);
    }//GEN-LAST:event_a7MouseClicked

    private void a8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a8MouseClicked
        setAsientos(this.a8);
    }//GEN-LAST:event_a8MouseClicked

    private void a9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a9MouseClicked
        setAsientos(this.a9);
    }//GEN-LAST:event_a9MouseClicked

    private void a10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a10MouseClicked
        setAsientos(this.a10);
    }//GEN-LAST:event_a10MouseClicked

    private void a11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a11MouseClicked
        setAsientos(this.a11);
    }//GEN-LAST:event_a11MouseClicked

    private void a12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a12MouseClicked
        setAsientos(this.a12);
    }//GEN-LAST:event_a12MouseClicked

    private void a13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a13MouseClicked
        setAsientos(this.a13);
    }//GEN-LAST:event_a13MouseClicked

    private void a14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a14MouseClicked
        setAsientos(this.a14);    }//GEN-LAST:event_a14MouseClicked

    private void a15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a15MouseClicked
        setAsientos(this.a15);    }//GEN-LAST:event_a15MouseClicked

    private void a16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a16MouseClicked
        setAsientos(this.a16);    }//GEN-LAST:event_a16MouseClicked

    private void a17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a17MouseClicked
        setAsientos(this.a17);    }//GEN-LAST:event_a17MouseClicked

    private void a18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a18MouseClicked
        setAsientos(this.a18);    }//GEN-LAST:event_a18MouseClicked

    private void a19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a19MouseClicked
        setAsientos(this.a19);    }//GEN-LAST:event_a19MouseClicked

    private void a20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a20MouseClicked
        setAsientos(this.a20);    }//GEN-LAST:event_a20MouseClicked

    private void a21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a21MouseClicked
        setAsientos(this.a21);    }//GEN-LAST:event_a21MouseClicked

    private void a22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a22MouseClicked
        setAsientos(this.a22);    }//GEN-LAST:event_a22MouseClicked

    private void a23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a23MouseClicked
        setAsientos(this.a23);    }//GEN-LAST:event_a23MouseClicked

    private void a24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a24MouseClicked
        setAsientos(this.a24);    }//GEN-LAST:event_a24MouseClicked

    private void a25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a25MouseClicked
        setAsientos(this.a25);
    }//GEN-LAST:event_a25MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ClienteVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a10;
    private javax.swing.JLabel a11;
    private javax.swing.JLabel a12;
    private javax.swing.JLabel a13;
    private javax.swing.JLabel a14;
    private javax.swing.JLabel a15;
    private javax.swing.JLabel a16;
    private javax.swing.JLabel a17;
    private javax.swing.JLabel a18;
    private javax.swing.JLabel a19;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a20;
    private javax.swing.JLabel a21;
    private javax.swing.JLabel a22;
    private javax.swing.JLabel a23;
    private javax.swing.JLabel a24;
    private javax.swing.JLabel a25;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a5;
    private javax.swing.JLabel a6;
    private javax.swing.JLabel a7;
    private javax.swing.JLabel a8;
    private javax.swing.JLabel a9;
    private javax.swing.JLabel cerrarSesionB;
    private javax.swing.JPanel configPanel;
    private javax.swing.JTabbedPane configTabPanel;
    private javax.swing.JPanel cuentasTabPanel;
    private com.toedter.calendar.JDateChooser fechaViaje;
    private javax.swing.JRadioButton horario1;
    private javax.swing.JRadioButton horario2;
    private javax.swing.JRadioButton horario3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel modCuenta_user;
    private javax.swing.JComboBox<String> sucDestinoComboBox;
    private javax.swing.JComboBox<String> sucOrigenComboBox;
    private javax.swing.JPanel usuariosPanel;
    // End of variables declaration//GEN-END:variables
}
