/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import chooseandtravel.Sistema;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Ventana Login del Software
 * 
 * @author Carlo Bernucci, Javier Nualart
 * @version 3.1
 */
public class Login extends javax.swing.JFrame {

    Sistema sistema = new Sistema();

    /**
     *
     */
    public Login() {
        sistema.inicio();
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inputUser = new javax.swing.JTextField();
        inputPass = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JLabel();
        LogoCT = new javax.swing.JLabel();
        icoUser = new javax.swing.JLabel();
        icoPass = new javax.swing.JLabel();
        helpIcon = new javax.swing.JLabel();
        info1 = new javax.swing.JLabel();
        info2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Choose & Travel");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setEnabled(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(488, 300));

        inputUser.setBackground(new java.awt.Color(255, 255, 255));
        inputUser.setForeground(new java.awt.Color(153, 153, 153));
        inputUser.setText("Cuenta");
        inputUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputUserMouseClicked(evt);
            }
        });
        inputUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUserActionPerformed(evt);
            }
        });

        inputPass.setBackground(new java.awt.Color(255, 255, 255));
        inputPass.setForeground(new java.awt.Color(153, 153, 153));
        inputPass.setText("jPasswordField");
        inputPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputPassMouseClicked(evt);
            }
        });

        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/loginDefault.png"))); // NOI18N
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginButtonMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginButtonMouseEntered(evt);
            }
        });

        LogoCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ct2.1-100px.png"))); // NOI18N

        icoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/userIcon32x32.png"))); // NOI18N

        icoPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/passIcon32x32.png"))); // NOI18N

        helpIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/help-icon-17014.png"))); // NOI18N
        helpIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpIconMouseClicked(evt);
            }
        });

        info1.setText("El formato de cuenta es \"n.Apellido\" seguido de 2 digitos!");
        info1.setVisible(false);

        info2.setText("Para más informacion contactarse al 999-561-52-41");
        info2.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LogoCT)
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(loginButton)
                                .addGap(39, 39, 39))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(icoUser, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(icoPass, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inputPass)
                                    .addComponent(inputUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(helpIcon)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(info2)
                            .addComponent(info1))
                        .addContainerGap(27, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(icoUser, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputPass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(icoPass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loginButton)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LogoCT)
                        .addGap(162, 162, 162)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(info1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(info2))
                    .addComponent(helpIcon))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/loginHover.png"));
        this.loginButton.setIcon(ico);
    }//GEN-LAST:event_loginButtonMouseEntered

    private void loginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/loginDefault.png"));
        this.loginButton.setIcon(ico);
    }//GEN-LAST:event_loginButtonMouseExited

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        if (inputUser.getText().equals("Cuenta") || inputPass.getText().equals("JPasswordField")) {
            JOptionPane.showMessageDialog(this, "Contraseña o usuario mal ingresado","Error",JOptionPane.WARNING_MESSAGE);
        } else {
           if(sistema.login(inputUser.getText(), inputPass.getText(), sistema)){
               dispose();
           }else{
               JOptionPane.showMessageDialog(this, "Contraseña o usuario mal ingresado","Error",JOptionPane.WARNING_MESSAGE);
           }
        }
    }//GEN-LAST:event_loginButtonMouseClicked

    private void loginButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseReleased
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/loginDefault.png"));
        this.loginButton.setIcon(ico);
    }//GEN-LAST:event_loginButtonMouseReleased

    private void loginButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMousePressed
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/loginPressed.png"));
        this.loginButton.setIcon(ico);
    }//GEN-LAST:event_loginButtonMousePressed

    private void inputPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputPassMouseClicked
        if(!inputPass.getText().equals("jPasswordField")){
            
        }else{
            inputPass.setText("");
        }
        if (inputUser.getText().equals("")) {
            inputUser.setText("Cuenta");
        }
    }//GEN-LAST:event_inputPassMouseClicked

    private void inputUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUserActionPerformed

    private void inputUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputUserMouseClicked
        if(!inputUser.getText().equals("Cuenta")){ 
        }else{
            inputUser.setText("");
        }
        if (inputPass.getText().equals("")) {
            inputPass.setText("jPasswordField");
        }
    }//GEN-LAST:event_inputUserMouseClicked

    private void helpIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpIconMouseClicked
        if(this.info1.isVisible()&&this.info2.isVisible()){
            this.info1.setVisible(false);
            this.info2.setVisible(false);
        }else{
            this.info1.setVisible(true);
            this.info2.setVisible(true);
        }
    }//GEN-LAST:event_helpIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoCT;
    private javax.swing.JLabel helpIcon;
    private javax.swing.JLabel icoPass;
    private javax.swing.JLabel icoUser;
    private javax.swing.JLabel info1;
    private javax.swing.JLabel info2;
    private javax.swing.JPasswordField inputPass;
    private javax.swing.JTextField inputUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginButton;
    // End of variables declaration//GEN-END:variables
}
